name = "clash"
main = "src/index.js"
compatibility_date = "2026-05-26"
workers_dev = true
preview_urls = true

routes = [
	{ pattern = "vpn.awacat.cc", zone_name = "awacat.cc", custom_domain = true }
]

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "5e034b65d0eb49eaac71a447413dbc1a"
