export const DEFAULT_NODES = [
  {
    id: 'node-1',
    name: 'JP-中转机直连',
    type: 'hysteria2',
    server: 'jp.awacat.cc',
    port: 50000,
    password: 'neko233333',
    sni: 'jp.awacat.cc',
    skipCertVerify: false,
    enabled: true,
    sort: 0,
  },
  {
    id: 'node-2',
    name: 'JP-Softbank 中转',
    type: 'hysteria2',
    server: 'jp.awacat.cc',
    port: 50001,
    password: 'neko233333',
    sni: 'bing.com',
    skipCertVerify: true,
    enabled: true,
    sort: 1,
  },
  {
    id: 'node-3',
    name: 'JP-KDDI 中转',
    type: 'hysteria2',
    server: 'jp.awacat.cc',
    port: 50002,
    password: 'neko233333',
    sni: 'bing.com',
    skipCertVerify: true,
    enabled: true,
    sort: 2,
  },
  {
    id: 'node-4',
    name: 'JP-Softbank 直连',
    type: 'hysteria2',
    server: 'softbank88.xzcloudnode.sbs',
    port: 50393,
    password: 'neko233333',
    sni: 'bing.com',
    skipCertVerify: true,
    enabled: true,
    sort: 3,
  },
  {
    id: 'node-5',
    name: 'JP-KDDI 直连',
    type: 'hysteria2',
    server: 'kddi10gbps.xzcloudnode.sbs',
    port: 50393,
    password: 'neko233333',
    sni: 'bing.com',
    skipCertVerify: true,
    enabled: true,
    sort: 4,
  },
];

export const DEFAULT_RULES = {
  preset: 'loyalsoldier',
  customRules: [],
  defaultOutbound: 'proxy',
};
